eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7004
spring:
  application:
    name: eureka-feign
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        forceClosed: true
        sleepWindowInMilliseconds: 500000
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
  shareSecurityContext: true