server:
  port: 7001

spring:
  application:
    name: eureka-client
  boot:
    admin:
      client:
        url: "http://localhost:7012"
        instance:
          prefer-ip: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
      health:
        show-details: ALWAYS   #health endpoint是否必须显示全部细节
info:
    version: "@project.version@"
    groupId: "@project.groupId@"
    artifactId: "@project.artifactId@"
logging:
    path: "/java-log"
    level:
     root: info