eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7005
spring:
  application:
    name: service-zuul
zuul:
  routes:
     feign:
       path: /feign/**
       serviceId: eureka-feign
     ribbon:
        path: /ribbon/**
        serviceId: server-ribbon