server:
  port: 8761
spring:
  application:
    name: eurka-server

eureka:
  instance:
    hostname: localhost1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost2:8762/eureka/

