server:
  port: 8762

spring:
  application:
    name: eurka-server

eureka:
  instance:
    hostname: localhost2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost1:8761/eureka/

